name: Build and Deploy to Dev Server

on:
  push:
    branches:
      - main # Adjust the branch as per your workflow
      - hack-list-skeleton

jobs:
  build-and-deploy-hack-list:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup SSH Key
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Deploy to Dev Server
      env:
        DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
        DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
      run: |
        # SSH into the server and execute the deployment commands
        ssh -t -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_HOST << 'EOF'
          # Change directory to the project directory
          cd /home/github-deploy/hacklist/cms-sites

          # Pull the latest changes from GitHub
          git checkout hack-list-skeleton
          git pull origin hack-list-skeleton

          # Build the Docker image
          docker compose -f hacklist/docker-compose.yml -p hacklist up -d --build
        EOF
